# Generated by Django 5.0.4 on 2024-05-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreshPickApp', '0004_cart_created_at_cartitem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
